# Generated by Django 3.1.1 on 2020-10-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'author_table',
            },
        ),
    ]
